server:
  port: 8080
eureka:
  instance:
    hostname: server1.leemaster.cn
  client:
    service-url:
      defaultZone: http://server2.leemaster.cn:8080/youmoney/

  server:
    enable-self-preservation: false
